USE [master]
GO
/****** Object:  Database [school_db]   ******/
CREATE DATABASE [school_db]
GO
ALTER DATABASE [school_db] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [school_db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [school_db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [school_db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [school_db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [school_db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [school_db] SET ARITHABORT OFF 
GO
ALTER DATABASE [school_db] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [school_db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [school_db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [school_db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [school_db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [school_db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [school_db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [school_db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [school_db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [school_db] SET  ENABLE_BROKER 
GO
ALTER DATABASE [school_db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [school_db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [school_db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [school_db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [school_db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [school_db] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [school_db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [school_db] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [school_db] SET  MULTI_USER 
GO
ALTER DATABASE [school_db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [school_db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [school_db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [school_db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [school_db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [school_db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [school_db] SET QUERY_STORE = OFF
GO
USE [school_db]
GO
/****** Object:  Table [dbo].[Materiais]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Materiais](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](100) NOT NULL,
	[Tipo] [nvarchar](50) NOT NULL,
	[Quantidade] [int] NOT NULL,
	[Descricao] [nvarchar](255) NULL,
 CONSTRAINT [PK_Materiais] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservas]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservas](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[idUsuario] [int] NOT NULL,
	[idMaterial] [int] NOT NULL,
	[datRetirada] [smalldatetime] NOT NULL,
	[datEntrega] [smalldatetime] NOT NULL,
	[Status] [nvarchar](10) NULL,
 CONSTRAINT [PK_Reservas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Senha] [nvarchar](50) NOT NULL,
	[Tipo] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Reservas]  WITH CHECK ADD  CONSTRAINT [FK_Materiais] FOREIGN KEY([idMaterial])
REFERENCES [dbo].[Materiais] ([Id])
GO
ALTER TABLE [dbo].[Reservas] CHECK CONSTRAINT [FK_Materiais]
GO
ALTER TABLE [dbo].[Reservas]  WITH CHECK ADD  CONSTRAINT [FK_Usuarios] FOREIGN KEY([idUsuario])
REFERENCES [dbo].[Usuarios] ([Id])
GO
ALTER TABLE [dbo].[Reservas] CHECK CONSTRAINT [FK_Usuarios]
GO
USE [master]
GO
ALTER DATABASE [school_db] SET  READ_WRITE 
GO
